spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qlsjtm12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  profiles:
    include: oauth

  session:
    jdbc:
      initialize-schema: always

server:
  servlet:
    session:
      tracking-modes: cookie