spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qlsjtm12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create

  profiles:
    include: oauth

server:
  servlet:
    session:
      tracking-modes: cookie